apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Use remote kustomization instead of direct YAML
resources:
  - namespace.yaml  # Our custom namespace with Pod Security labels
  - upstream-manifests.yaml  # Stripped upstream without namespace

# Apply Talos-specific patches  
patches:
  - configmap-patch.yaml
  - storageclass-patch.yaml

commonLabels:
  app.kubernetes.io/name: local-path-provisioner
  app.kubernetes.io/version: v0.0.31
  app.kubernetes.io/managed-by: argocd