# ArgoCD configuration for path-based access
# This configures ArgoCD to work properly when accessed via /argocd path
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-server-config
  namespace: argocd
data:
  # URL configuration for path-based access
  url: "https://lab.techdufus.com/argocd"
  
  # Additional server configuration
  application.instanceLabelKey: argocd.argoproj.io/instance
  
  # OIDC configuration (can be added later if using GitHub/Google auth)
  # oidc.config: |
  #   name: GitHub
  #   issuer: https://token.actions.githubusercontent.com
  #   clientId: <your-client-id>
  #   clientSecret: <your-client-secret>
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: argocd
data:
  # Enable insecure mode since TLS is handled by Cloudflare
  server.insecure: "true"
  
  # Set base href for UI to work under /argocd path
  server.basehref: "/argocd"
  
  # Disable internal TLS
  server.disable.auth: "false"
  
  # Additional parameters for path-based routing
  server.rootpath: "/argocd"
  
---
# Service patch to ensure proper port exposure
apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 443
    targetPort: 8080
    protocol: TCP
    name: https
  selector:
    app.kubernetes.io/name: argocd-server