apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-token
  namespace: cloudflare-tunnel
type: Opaque
data:
  # Base64 encoded tunnel token from Cloudflare Zero Trust Dashboard
  # Get this from: https://one.dash.cloudflare.com/
  # Create a tunnel, copy the token, and base64 encode it
  # echo -n "your-tunnel-token-here" | base64
  token: ""  # Replace with your actual base64 encoded tunnel token