---
- name: "Docker: Ensure Home Assistant directory exists"
  file:
    path: "{{ homeassistant_docker_home }}"
    state: directory
    mode: 0755
    force: true
  become: true

- name: Start home-assistant Docker Image
  docker_container:
    name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:stable
    state: started
    published_ports:
      - "{{ homeassistant_host_port_80 }}:{{ homeassistant_docker_port_80 }}"
    volumes:
      - "{{ homeassistant_docker_home }}:/config"
    restart_policy: "unless-stopped"
    env:
      TZ: 'America/Chicago'
    force_kill: yes
    pull: yes
    privileged: yes
    detach: true
  become: yes

- name: "Docker: Deploy homeassistant Configuration"
  copy:
    src: "files/"
    dest: "{{ homeassistant_docker_home }}"
  become: yes
