apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: onepassworditems.onepassword.com
  labels:
    app.kubernetes.io/name: onepassword-operator
spec:
  group: onepassword.com
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              itemPath:
                type: string
                description: "Path to the 1Password item (vaults/vault-name/items/item-name)"
              secretKey:
                type: string
                description: "Key name in the target Kubernetes secret"
              secretName:
                type: string
                description: "Name of the Kubernetes secret to create/update"
              secretNamespace:
                type: string
                description: "Namespace for the Kubernetes secret (defaults to same as OnePasswordItem)"
              secretType:
                type: string
                description: "Type of Kubernetes secret (default: Opaque)"
                default: "Opaque"
              secretLabels:
                type: object
                additionalProperties:
                  type: string
                description: "Labels to apply to the created secret"
              secretAnnotations:
                type: object
                additionalProperties:
                  type: string
                description: "Annotations to apply to the created secret"
            required:
            - itemPath
            - secretKey
            - secretName
          status:
            type: object
            properties:
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    lastTransitionTime:
                      type: string
                      format: date-time
                    reason:
                      type: string
                    message:
                      type: string
                  required:
                  - type
                  - status
              lastSync:
                type: string
                format: date-time
              secretRef:
                type: object
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Secret
      type: string
      description: The name of the created Kubernetes secret
      jsonPath: .spec.secretName
    - name: Status
      type: string
      description: The status of the OnePasswordItem
      jsonPath: .status.conditions[?(@.type=="Ready")].status
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: onepassworditems
    singular: onepassworditem
    kind: OnePasswordItem
    shortNames:
    - opi
    - opitem
---
# Validating admission webhook configuration
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionWebhook
metadata:
  name: onepassword-operator-webhook
  labels:
    app.kubernetes.io/name: onepassword-operator
webhooks:
- name: validate.onepassworditem.onepassword.com
  clientConfig:
    service:
      name: onepassword-operator-webhook
      namespace: onepassword-operator
      path: /validate-onepassworditem
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: ["onepassword.com"]
    apiVersions: ["v1"]
    resources: ["onepassworditems"]
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  failurePolicy: Fail