apiVersion: v1
kind: Namespace
metadata:
  name: onepassword-operator
  labels:
    name: onepassword-operator
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
  annotations:
    description: "1Password Secret Operator namespace for secure secret management"
---
# Network policy to restrict 1Password operator communication
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: onepassword-operator-policy
  namespace: onepassword-operator
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: onepassword-operator
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow Kubernetes API server communication
  - from:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: TCP
      port: 8443
  # Allow metrics scraping from monitoring namespace
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
    ports:
    - protocol: TCP
      port: 8080
  egress:
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  # Allow HTTPS to 1Password API
  - to: []
    ports:
    - protocol: TCP
      port: 443
  # Allow Kubernetes API access
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: TCP
      port: 6443