apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflare
spec:
  replicas: 1  # Dev uses only 1 replica instead of 2
  template:
    spec:
      containers:
      - name: cloudflared
        resources:
          requests:
            cpu: 50m      # Lower resources for dev
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi