apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  # Core infrastructure
  - apps/gateway-api-crds.yaml  # Gateway API CRDs
  - apps/metallb.yaml           # LoadBalancer provider
  - apps/metallb-config.yaml    # MetalLB IP pool configuration
  - apps/traefik.yaml           # Gateway controller
  - apps/gateway-config.yaml    # Gateway and HTTPRoutes

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: argocd