
# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.0.20.49
    - 172.16.0.0/12

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
