apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-tunnel-config
  namespace: cloudflare-tunnel
data:
  config.yaml: |
    tunnel: techdufus-home-lab
    credentials-file: /etc/cloudflared/creds/credentials.json
    
    # Ingress rules - these map external domains to internal services
    ingress:
      # ArgoCD
      - hostname: argocd.lab.techdufus.com
        service: http://argocd-server.argocd.svc.cluster.local:80
        originRequest:
          httpHostHeader: argocd.home.io
      
      # Home Assistant  
      - hostname: ha.lab.techdufus.com
        service: http://home-assistant.home-assistant.svc.cluster.local:8123
        originRequest:
          httpHostHeader: ha.home.io
      
      # Future service example - Jellyfin
      - hostname: jellyfin.lab.techdufus.com
        service: http://jellyfin.jellyfin.svc.cluster.local:8096
        originRequest:
          httpHostHeader: jellyfin.home.io
      
      # Catch-all rule (required)
      - service: http_status:404
    
    # Logging and metrics
    log:
      level: info
    
    metrics: 0.0.0.0:9090