apiVersion: v1
kind: PersistentVolume
metadata:
  name: mattermost-data
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-shared
  mountOptions:
    - hard
  nfs:
    server: 10.0.0.254
    path: /var/nfs/shared/Homelab/mattermost-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mattermost-data
  namespace: mattermost
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-shared
  resources:
    requests:
      storage: 50Gi
  volumeName: mattermost-data
