apiVersion: v1
kind: Service
metadata:
  name: mattermost-postgres
  namespace: mattermost
  labels:
    app: mattermost-postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    app: mattermost-postgres
