---
- hosts: containerhost
  vars:
    roles_path: /etc/ansible/roles:../roles
    inventory: ../hosts.ini
  become: true

  roles:
    - { role: common, tags: common }
    - { role: docker, tags: docker }
    - { role: dashy, tags: dashy }
    # - { role: home-assistant, tags: home-assistant }
    - { role: portainer, tags: portainer }
    - { role: minecraft, tags: minecraft }
