apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: immich
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: immich
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Create before application
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      # Start with 40Gi for photo library - can expand later
      # This stores uploaded photos, thumbnails, and processed data
      storage: 40Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-ml-cache
  namespace: immich
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: ml-cache
    app.kubernetes.io/part-of: immich
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Create before application
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      # Cache for machine learning models
      storage: 10Gi