apiVersion: v1
kind: Secret
metadata:
  name: immich-postgres-secret
  namespace: immich
  labels:
    app.kubernetes.io/name: immich-postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: immich
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Create before database cluster
type: Opaque
stringData:
  # Database credentials for Immich PostgreSQL cluster
  # TODO: Replace with 1Password secret reference when 1Password operator is available
  username: immich
  password: "immich-secure-password-change-me"
  database: immich
  
  # Connection string for applications
  # Format: postgresql://username:password@host:port/database
  # The host will be: immich-postgres-rw.immich.svc.cluster.local:5432
  postgres-uri: "postgresql://immich:immich-secure-password-change-me@immich-postgres-rw.immich.svc.cluster.local:5432/immich"