apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgres
  namespace: immich
  labels:
    app.kubernetes.io/name: immich-postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: immich
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # Deploy after namespace, before application
spec:
  # Use CloudNativePG base image (pgvector will be installed if available)
  imageName: ghcr.io/cloudnative-pg/postgresql:16.6-3
  
  # Single instance for homelab (can scale later)
  instances: 1
  
  # PostgreSQL configuration for Immich
  postgresql:
    shared_preload_libraries:
      - "vector.so"
    parameters:
      # Performance tuning for homelab
      max_connections: "200"
      shared_buffers: "256MB"
      effective_cache_size: "1GB"
      work_mem: "4MB"
  
  # Bootstrap configuration
  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-postgres-secret
      encoding: "UTF8"
      localeCollate: "C"
      localeCType: "C"
      postInitApplicationSQL:
        # Create extensions required by Immich
        - "CREATE EXTENSION IF NOT EXISTS \"vector\";"
        - "CREATE EXTENSION IF NOT EXISTS \"cube\" CASCADE;"
        - "CREATE EXTENSION IF NOT EXISTS \"earthdistance\" CASCADE;"
        - "CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\" CASCADE;"
  
  # Storage configuration
  storage:
    size: 10Gi
    storageClass: local-path
  
  # Resources for homelab environment
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi