apiVersion: v1
kind: ConfigMap
metadata:
  name: dashy-config
  namespace: dashy
  labels:
    app.kubernetes.io/name: dashy
    app.kubernetes.io/component: config
    app.kubernetes.io/managed-by: argocd
data:
  conf.yml: |
    # Dashy Configuration for TechDufus Homelab - Clean Version
    pageInfo:
      title: TechDufus Homelab
      description: Welcome to the Homelab!
      navLinks:
        - title: GitHub
          path: https://github.com/TechDufus/home.io
        - title: Documentation
          path: https://dashy.to/docs
    
    appConfig:
      theme: colorful
      layout: auto
      iconSize: medium
      language: en
      statusCheck: false
      statusCheckInterval: 0
      disableUpdateChecks: true
      disableContextMenu: false
      defaultOpeningMethod: newtab
      preventWriteToDisk: false
      disableConfiguration: false
      allowConfigEdit: true
      enableErrorReporting: false
      enableFontAwesome: true
      enableMaterialDesignIcons: true
      webSearch:
        searchEngine: google
        openingMethod: newtab
      hideComponents:
        hideSettings: false
        hideFooter: false
      auth:
        enableGuestAccess: true
    
    sections:
      # Proxmox CPU Monitoring
      - name: ProxMox Current CPU
        icon: hl-proxmox
        layout: grid
        widgets:
          - type: gl-current-cpu
            options:
              hostname: http://10.0.20.3:61208
      
      # Proxmox RAM Monitoring  
      - name: ProxMox Current RAM
        icon: hl-proxmox
        layout: grid
        widgets:
          - type: gl-current-mem
            options:
              hostname: http://10.0.20.3:61208
      
      # Core Services
      - name: Services
        icon: hl-wetty
        displayData:
          rows: 2
        items:
          - title: ProxMox
            description: ProxMox VE node
            url: https://10.0.20.3:8006/
            icon: hl-proxmox
            target: newtab
            statusCheckAllowInsecure: true
            
          - title: Pihole-Primary
            description: Primary Pi-Hole DNS server
            url: http://10.0.0.99/admin
            icon: hl-pihole
            target: newtab
            
          - title: Home Gateway
            description: Router / Gateway for my Home
            url: http://10.0.0.1/
            icon: hl-router
            target: newtab
            
          - title: ArgoCD
            description: GitOps Deployment
            url: https://lab.techdufus.com/argocd
            icon: hl-argocd
            target: newtab
            
          - title: Traefik
            description: Gateway Controller
            url: http://traefik.traefik.svc.cluster.local:9000
            icon: hl-traefik
            target: newtab
      
      # Proxmox Statistics History
      - name: ProxMox Stat History
        icon: hl-proxmox
        layout: grid
        displayData:
          itemSize: small
          sectionLayout: grid
          cols: 2
          rows: 3
        widgets:
          - type: gl-cpu-history
            options:
              hostname: http://10.0.20.3:61208
              limit: 400
          - type: gl-mem-history
            options:
              hostname: http://10.0.20.3:61208
              limit: 400
      
      # Applications
      - name: Applications
        icon: fas fa-rocket
        displayData:
          sortBy: default
          rows: 2
          cols: 3
          collapsed: false
        items:
          - title: Immich
            description: Photo Management
            url: https://photos.techdufus.com
            icon: fas fa-images
            target: newtab
            statusCheck: false
            
          - title: Dashy
            description: This Dashboard
            url: https://lab.techdufus.com
            icon: fas fa-tachometer-alt
            target: sametab
            statusCheck: false
            
          - title: Cloudflare
            description: DNS & Tunnel Management
            url: https://dash.cloudflare.com
            icon: fas fa-cloud
            target: newtab
            statusCheck: false
            
          - title: GitHub
            description: Code Repository
            url: https://github.com/TechDufus/home.io
            icon: fab fa-github
            target: newtab
            statusCheck: false
            
          - title: 1Password
            description: Password Manager
            url: https://my.1password.com
            icon: fas fa-key
            target: newtab
            statusCheck: false
      
      # Kubernetes Resources
      - name: Kubernetes
        icon: hl-kubernetes
        displayData:
          sortBy: default
          rows: 1
          cols: 3
          collapsed: false
        items:
          - title: MetalLB
            description: Load Balancer
            icon: fas fa-balance-scale
            statusCheck: false
            
          - title: CloudNativePG
            description: PostgreSQL Operator
            icon: hl-postgres
            statusCheck: false
            
          - title: Local Path Storage
            description: Storage Provider
            icon: fas fa-hdd
            statusCheck: false
      
      # Documentation Links
      - name: Documentation
        icon: fas fa-book
        displayData:
          sortBy: default
          rows: 1
          cols: 4
          collapsed: true
        items:
          - title: Proxmox Forum
            url: https://forum.proxmox.com
            icon: hl-proxmox
            target: newtab
            statusCheck: false
            
          - title: Pi-hole Docs
            url: https://docs.pi-hole.net
            icon: hl-pihole
            target: newtab
            statusCheck: false
            
          - title: Kubernetes Docs
            url: https://kubernetes.io/docs
            icon: hl-kubernetes
            target: newtab
            statusCheck: false
            
          - title: Dashy Docs
            url: https://dashy.to/docs
            icon: fas fa-file-alt
            target: newtab
            statusCheck: false
      
      # Local Time Display
      - name: Local Time
        displayData:
          collapsed: false
        widgets:
          - type: clock
            options:
              timeZone: America/Chicago
              format: en-US
              hideDate: false