apiVersion: v1
kind: ConfigMap
metadata:
  name: dashy-config
  namespace: dashy
  labels:
    app.kubernetes.io/name: dashy
    app.kubernetes.io/component: config
    app.kubernetes.io/managed-by: argocd
data:
  conf.yml: |
    # Dashy Configuration for TechDufus Homelab
    pageInfo:
      title: TechDufus Homelab
      description: Welcome to the Homelab!
      navLinks:
        - title: GitHub
          path: https://github.com/TechDufus/home.io
        - title: Documentation
          path: https://dashy.to/docs
      footerText: ''
    
    appConfig:
      theme: colorful
      layout: auto
      iconSize: medium
      language: en
      statusCheck: true
      statusCheckInterval: 30
      defaultOpeningMethod: newtab
      webSearch:
        searchEngine: google
        openingMethod: newtab
      preventWriteToDisk: false
      disableConfiguration: false
      allowConfigEdit: true
      enableErrorReporting: false
      enableFontAwesome: true
      enableMaterialDesignIcons: true
      hideComponents:
        hideSettings: false
        hideFooter: false
      auth:
        enableGuestAccess: true
      
    sections:
      # System Monitoring Widgets
      - name: System Resources
        icon: fas fa-tachometer-alt
        displayData:
          collapsed: false
          cols: 2
        widgets:
          - type: clock
            options:
              timeZone: America/Chicago
              format: en-US
              hideDate: false
          - type: weather
            options:
              apiKey: ''
              city: Chicago
              units: imperial
              hideDetails: false
      
      # Pi-hole Statistics
      - name: Pi-hole Statistics
        icon: hl-pihole
        displayData:
          collapsed: false
          cols: 1
        widgets:
          - type: pi-hole-stats
            updateInterval: 30
            options:
              hostname: http://10.0.0.99
              useProxy: true
              hideInfo: false
              hideChart: false
              hideStatus: false
      
      # Core Services
      - name: Infrastructure
        icon: fas fa-server
        displayData:
          sortBy: default
          rows: 2
          cols: 3
          collapsed: false
        items:
          - title: Proxmox VE
            description: Virtualization Platform
            url: https://10.0.20.3:8006/
            icon: hl-proxmox
            target: newtab
            statusCheck: true
            statusCheckUrl: https://10.0.20.3:8006
            statusCheckAllowInsecure: true
            statusCheckAcceptCodes: '401,200'
            
          - title: Pi-hole Admin
            description: Primary DNS Server
            url: http://10.0.0.99/admin
            icon: hl-pihole
            target: newtab
            statusCheck: true
            statusCheckUrl: http://10.0.0.99
            
          - title: Home Gateway
            description: Router / Gateway
            url: http://10.0.0.1/
            icon: hl-router
            target: newtab
            statusCheck: true
            
          - title: ArgoCD
            description: GitOps Deployment
            url: https://argocd.techdufus.com
            icon: hl-argocd
            target: newtab
            statusCheck: true
            
          - title: Traefik
            description: Gateway Controller
            url: http://traefik.traefik.svc.cluster.local:9000
            icon: hl-traefik
            target: newtab
            statusCheck: false
      
      # Applications
      - name: Applications
        icon: fas fa-rocket
        displayData:
          sortBy: default
          rows: 2
          cols: 3
          collapsed: false
        items:
          - title: Immich
            description: Photo Management
            url: https://photos.techdufus.com
            icon: hl-immich
            target: newtab
            statusCheck: true
            
          - title: Dashy
            description: This Dashboard
            url: https://home.techdufus.com
            icon: hl-dashy
            target: sametab
            
          - title: Cloudflare
            description: DNS & Tunnel Management
            url: https://dash.cloudflare.com
            icon: hl-cloudflare
            target: newtab
            
          - title: GitHub
            description: Code Repository
            url: https://github.com/TechDufus/home.io
            icon: hl-github
            target: newtab
            
          - title: 1Password
            description: Password Manager
            url: https://my.1password.com
            icon: hl-onepassword
            target: newtab
      
      # Kubernetes Resources
      - name: Kubernetes
        icon: hl-kubernetes
        displayData:
          sortBy: default
          rows: 1
          cols: 3
          collapsed: false
        items:
          - title: MetalLB
            description: Load Balancer
            icon: hl-metallb
            target: newtab
            
          - title: CloudNativePG
            description: PostgreSQL Operator
            icon: hl-postgres
            target: newtab
            
          - title: Local Path Storage
            description: Storage Provider
            icon: fas fa-hdd
            target: newtab
      
      # Quick Links / Documentation
      - name: Documentation
        icon: fas fa-book
        displayData:
          sortBy: default
          rows: 1
          cols: 4
          collapsed: true
        items:
          - title: Proxmox Forum
            url: https://forum.proxmox.com
            icon: hl-proxmox
            target: newtab
            
          - title: Pi-hole Docs
            url: https://docs.pi-hole.net
            icon: hl-pihole
            target: newtab
            
          - title: Kubernetes Docs
            url: https://kubernetes.io/docs
            icon: hl-kubernetes
            target: newtab
            
          - title: Dashy Docs
            url: https://dashy.to/docs
            icon: hl-dashy
            target: newtab