apiVersion: v1
kind: ConfigMap
metadata:
  name: dashy-config
  namespace: dashy
  labels:
    app.kubernetes.io/name: dashy
    app.kubernetes.io/component: config
    app.kubernetes.io/managed-by: argocd
data:
  conf.yml: |
    # Dashy Configuration for TechDufus Homelab
    pageInfo:
      title: TechDufus Homelab
      description: Welcome to the Homelab!
      navLinks:
        - title: GitHub
          path: https://github.com/TechDufus/home.io
        - title: Documentation
          path: https://dashy.to/docs
      footerText: ''
    
    appConfig:
      theme: colorful
      layout: auto
      iconSize: medium
      language: en
      statusCheck: false
      statusCheckInterval: 30
      defaultOpeningMethod: newtab
      webSearch:
        searchEngine: google
        openingMethod: newtab
      preventWriteToDisk: false
      disableConfiguration: false
      allowConfigEdit: true
      enableErrorReporting: false
      enableFontAwesome: true
      enableMaterialDesignIcons: true
      hideComponents:
        hideSettings: false
        hideFooter: false
      auth:
        enableGuestAccess: true
      customCss: ''
      
    sections:
      # System Monitoring Widgets
      - name: System Resources
        icon: fas fa-tachometer-alt
        displayData:
          collapsed: false
          cols: 1
        widgets:
          - type: clock
            options:
              timeZone: America/Chicago
              format: en-US
              hideDate: false
      
      # Core Services
      - name: Infrastructure
        icon: fas fa-server
        displayData:
          sortBy: default
          rows: 2
          cols: 3
          collapsed: false
        items:
          - title: Proxmox VE
            description: Virtualization Platform
            url: https://10.0.20.3:8006/
            icon: si-proxmox
            target: newtab
            
          - title: Pi-hole Admin
            description: Primary DNS Server
            url: http://10.0.0.99/admin
            icon: si-pihole
            target: newtab
            
          - title: Home Gateway
            description: Router / Gateway
            url: http://10.0.0.1/
            icon: fas fa-network-wired
            target: newtab
            
          - title: ArgoCD
            description: GitOps Deployment
            url: https://argocd.techdufus.com
            icon: si-argo
            target: newtab
            
          - title: Traefik
            description: Gateway Controller
            url: http://traefik.traefik.svc.cluster.local:9000
            icon: si-traefikmesh
            target: newtab
      
      # Applications
      - name: Applications
        icon: fas fa-rocket
        displayData:
          sortBy: default
          rows: 2
          cols: 3
          collapsed: false
        items:
          - title: Immich
            description: Photo Management
            url: https://photos.techdufus.com
            icon: fas fa-images
            target: newtab
            
          - title: Dashy
            description: This Dashboard
            url: https://home.techdufus.com
            icon: fas fa-tachometer-alt
            target: sametab
            
          - title: Cloudflare
            description: DNS & Tunnel Management
            url: https://dash.cloudflare.com
            icon: si-cloudflare
            target: newtab
            
          - title: GitHub
            description: Code Repository
            url: https://github.com/TechDufus/home.io
            icon: si-github
            target: newtab
            
          - title: 1Password
            description: Password Manager
            url: https://my.1password.com
            icon: si-onepassword
            target: newtab
      
      # Kubernetes Resources
      - name: Kubernetes
        icon: si-kubernetes
        displayData:
          sortBy: default
          rows: 1
          cols: 3
          collapsed: false
        items:
          - title: MetalLB
            description: Load Balancer
            icon: fas fa-balance-scale
            target: newtab
            
          - title: CloudNativePG
            description: PostgreSQL Operator
            icon: si-postgresql
            target: newtab
            
          - title: Local Path Storage
            description: Storage Provider
            icon: fas fa-hdd
            target: newtab
      
      # Quick Links / Documentation
      - name: Documentation
        icon: fas fa-book
        displayData:
          sortBy: default
          rows: 1
          cols: 4
          collapsed: true
        items:
          - title: Proxmox Forum
            url: https://forum.proxmox.com
            icon: si-proxmox
            target: newtab
            
          - title: Pi-hole Docs
            url: https://docs.pi-hole.net
            icon: si-pihole
            target: newtab
            
          - title: Kubernetes Docs
            url: https://kubernetes.io/docs
            icon: si-kubernetes
            target: newtab
            
          - title: Dashy Docs
            url: https://dashy.to/docs
            icon: fas fa-tachometer-alt
            target: newtab