apiVersion: v1
kind: Service
metadata:
  name: dashy
  namespace: dashy
  labels:
    app.kubernetes.io/name: dashy
    app.kubernetes.io/component: dashboard
    app.kubernetes.io/managed-by: argocd
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: dashy
    app.kubernetes.io/component: dashboard
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP