apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: lab-gateway
  namespace: traefik
spec:
  gatewayClassName: traefik
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All  # Allow routes from all namespaces
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: lab-techdufus-paths
  namespace: traefik
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: lab-gateway
      namespace: traefik
  hostnames:
    - lab.techdufus.com
  rules:
    # ArgoCD at /argocd
    - matches:
        - path:
            type: PathPrefix
            value: /argocd
      backendRefs:
        - group: ""
          kind: Service
          name: argocd-server
          namespace: argocd
          port: 80
          weight: 1
    
    # Homarr at /dashboard
    - matches:
        - path:
            type: PathPrefix
            value: /dashboard
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - group: ""
          kind: Service
          name: homarr
          namespace: homarr
          port: 7575
          weight: 1
    
    # Homarr init and static assets (catch-all for Homarr paths)
    - matches:
        - path:
            type: PathPrefix
            value: /init
        - path:
            type: PathPrefix
            value: /_next
        - path:
            type: PathPrefix
            value: /api
        - path:
            type: PathPrefix
            value: /favicon.ico
        - path:
            type: PathPrefix
            value: /logo
        - path:
            type: PathPrefix
            value: /manifest.webmanifest
      backendRefs:
        - group: ""
          kind: Service
          name: homarr
          namespace: homarr
          port: 7575
          weight: 1
    
    # Root path - Homarr dashboard
    - matches:
        - path:
            type: Exact
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: homarr
          namespace: homarr
          port: 7575
          weight: 1
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-traefik-routes
  namespace: argocd
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: traefik
  to:
    - group: ""
      kind: Service
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-traefik-routes
  namespace: homarr
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: traefik
  to:
    - group: ""
      kind: Service