# Global values for dev environment
environment: dev
domain: home.techdufus.com

# Common labels applied to all resources
labels:
  environment: dev
  managed-by: argocd

# Default resource limits for dev
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi