apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflare
data:
  config.yaml: |
    # Cloudflare Tunnel configuration
    tunnel: homelab-tunnel
    credentials-file: /etc/cloudflared/creds/credentials.json
    
    # Metrics server for monitoring
    metrics: 0.0.0.0:2000
    
    # No TLS verification for local services
    noTLSVerify: true
    
    # Ingress rules - route traffic to services
    ingress:
      # ArgoCD
      - hostname: argocd.home.techdufus.com
        service: https://argocd-server.argocd.svc.cluster.local:443
        originRequest:
          noTLSVerify: true
      
      # N8N
      - hostname: n8n.home.techdufus.com
        service: http://n8n.n8n.svc.cluster.local:5678
        originRequest:
          noTLSVerify: true
          httpHostHeader: n8n.home.techdufus.com
      
      # Future: Pi-hole
      - hostname: pihole.home.techdufus.com
        service: http://pihole-web.pihole.svc.cluster.local:80
        originRequest:
          noTLSVerify: true
      
      # Future: Home Assistant
      - hostname: homeassistant.home.techdufus.com
        service: http://home-assistant.home-assistant.svc.cluster.local:8123
        originRequest:
          noTLSVerify: true
          httpHostHeader: homeassistant.home.techdufus.com
      
      # Catch-all rule
      - service: http_status:404