apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-credentials
  namespace: cloudflare
type: Opaque
stringData:
  # This is a placeholder - the actual credentials.json should be created from:
  # 1. Create a tunnel in Cloudflare: cloudflared tunnel create homelab-tunnel
  # 2. Copy the generated credentials.json content here
  # 3. Or better: use External Secrets Operator to pull from 1Password
  credentials.json: |
    {
      "AccountTag": "YOUR_ACCOUNT_TAG",
      "TunnelSecret": "YOUR_TUNNEL_SECRET",
      "TunnelID": "YOUR_TUNNEL_ID"
    }