---
- name: "Install the latest version of the Docker Engine"
  block:
    - name: "Docker: Download gpg key"
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: "{{ docker_gpg_file }}"

    - name: "Docker: Import gpg key"
      shell: |
        cat {{ docker_gpg_file }} | gpg --dearmor | tee {{ docker_gpg_keyring }} > /dev/null

    - name: "Docker: Remove gpg key"
      file:
        state: absent
        path: "{{ docker_gpg_file }}"

    - name: "Docker: Add Docker repository"
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: "Docker: Install Docker Prerequisites"
      block:
      - name: "Docker: Install Apt Prerequisites"
        apt:
          name: "{{ item }}"
          state: present
        loop:
          - python3
          - python3-pip
      
      - name: "Docker: Install Pip Prerequisites"
        pip:
          name: "{{ item }}"
          state: present
        loop:
          - docker
      
    - name: Installing Docker Engine
      apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - docker-ce
  become: yes

- name: "Docker: Ensure Heimdall directory exists"
  file:
    path: "{{ heimdall_docker_home }}"
    state: directory
    mode: 0755
  become: yes

- name: Start Heimdall Docker Image
  docker_container:
    name: heimdall
    image: linuxserver/heimdall
    state: started
    published_ports:
      - "{{ heimdall_host_port_80 }}:{{ heimdall_docker_port_80 }}"
      - "{{ heimdall_host_port_443 }}:{{ heimdall_docker_port_443 }}"
    volumes:
      - "{{ heimdall_docker_home }}:/config"
    restart_policy: always
    detach: true
    pid_mode: host
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "--connect-timeout", "1", "--max-time", "1", "http://localhost:{{ heimdall_host_port_80 }}/health"]
  become: yes

- name: "Docker: Deploy Heimdall Configuration"
  copy:
    src: "files/"
    dest: "{{ heimdall_docker_home }}"
  become: yes
  
    