apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-services
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      # Gateway API and routing infrastructure
      - name: gateway-api-crds
        repoURL: https://github.com/kubernetes-sigs/gateway-api
        targetRevision: v1.2.1
        path: config/crd
        namespace: default
        syncOptions: 
          - CreateNamespace=false
          - ServerSideApply=true
      - name: traefik
        repoURL: https://traefik.github.io/charts
        chart: traefik
        targetRevision: "33.2.0"
        namespace: traefik
        valueFiles:
          - $values/kubernetes/argocd/values/traefik.yaml
      - name: gateway-config
        repoURL: https://github.com/TechDufus/home.io
        targetRevision: main
        path: kubernetes/argocd/manifests/gateway
        namespace: traefik
      
      # Load balancing infrastructure  
      - name: metallb
        repoURL: https://metallb.github.io/metallb
        chart: metallb
        targetRevision: "0.14.8"
        namespace: metallb-system
        valueFiles:
          - $values/kubernetes/argocd/values/metallb.yaml
      - name: metallb-config
        repoURL: https://github.com/TechDufus/home.io
        targetRevision: main
        path: kubernetes/argocd/manifests/metallb
        namespace: metallb-system
      
      # Storage infrastructure
      - name: local-path-provisioner
        repoURL: https://github.com/TechDufus/home.io
        targetRevision: main
        path: kubernetes/argocd/manifests/local-path-provisioner
        namespace: local-path-storage
      
      # Metrics infrastructure  
      - name: metrics-server
        repoURL: https://kubernetes-sigs.github.io/metrics-server/
        chart: metrics-server
        targetRevision: "3.12.2"
        namespace: kube-system
        valueFiles:
          - $values/kubernetes/argocd/values/metrics-server.yaml
      
      # Network access
      - name: cloudflared
        repoURL: https://github.com/TechDufus/home.io
        targetRevision: main
        path: kubernetes/argocd/manifests/cloudflared
        namespace: cloudflare
  template:
    metadata:
      name: 'platform-{{.name}}'
      namespace: argocd
      labels:
        app.kubernetes.io/managed-by: applicationset
        app.kubernetes.io/part-of: platform
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      sources:
        - repoURL: '{{.repoURL}}'
          targetRevision: '{{.targetRevision}}'
          {{- if .chart }}
          chart: '{{.chart}}'
          helm:
            releaseName: '{{.name}}'
            {{- if .valueFiles }}
            valueFiles: {{.valueFiles | toJson}}
            {{- end}}
          {{- else }}
          path: '{{.path}}'
          {{- end}}
        {{- if .valueFiles }}
        - repoURL: https://github.com/TechDufus/home.io
          targetRevision: main
          ref: values
        {{- end}}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          {{- if .syncOptions }}
          {{- range .syncOptions }}
          - '{{.}}'
          {{- end}}
          {{- else }}
          - ServerSideApply=true
          {{- end}}
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
      revisionHistoryLimit: 10