apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # Helm chart source
    - chart: n8n
      repoURL: https://8gears.container-registry.com/chartrepo/library
      targetRevision: 0.23.0
      helm:
        releaseName: n8n
        valueFiles:
          - $values/argocd/overlays/ENVIRONMENT_PLACEHOLDER/values/global.yaml
          - $values/argocd/overlays/ENVIRONMENT_PLACEHOLDER/values/n8n.yaml
    # Values from Git repo
    - repoURL: https://github.com/TechDufus/home.io
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10