# Development Environment Secret References
# These OnePasswordItem resources create Kubernetes secrets from 1Password vault items

---
# ArgoCD Admin Password
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: argocd-admin-password
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/component: secret
    environment: dev
spec:
  itemPath: "vaults/cicd/items/dev-argocd-admin"
  secretKey: "argocd.admin.password"
  secretName: "argocd-initial-admin-secret"
  secretType: "Opaque"
  secretLabels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/managed-by: onepassword-operator
  secretAnnotations:
    onepassword.com/item-path: "vaults/cicd/items/dev-argocd-admin"
    onepassword.com/sync-interval: "60s"

---
# ArgoCD GitHub Repository Access Token
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: argocd-repo-token
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/component: secret
    environment: dev
spec:
  itemPath: "vaults/cicd/items/github-argocd-token"
  secretKey: "password"
  secretName: "argocd-repo-credentials"
  secretType: "Opaque"
  secretLabels:
    argocd.argoproj.io/secret-type: repository
  secretAnnotations:
    onepassword.com/item-path: "vaults/cicd/items/github-argocd-token"

---
# Cloudflare API Token for Cert-Manager DNS Challenge
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: secret
    environment: dev
spec:
  itemPath: "vaults/cicd/items/dev-cloudflare-dns-token"
  secretKey: "api-token"
  secretName: "cloudflare-api-token"
  secretType: "Opaque"
  secretLabels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/managed-by: onepassword-operator
  secretAnnotations:
    onepassword.com/item-path: "vaults/cicd/items/dev-cloudflare-dns-token"

---
# External-DNS Cloudflare API Token
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: external-dns-cloudflare-token
  namespace: external-dns
  labels:
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/component: secret
    environment: dev
spec:
  itemPath: "vaults/cicd/items/dev-cloudflare-dns-token"
  secretKey: "api-token"
  secretName: "external-dns-cloudflare"
  secretType: "Opaque"
  secretLabels:
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/managed-by: onepassword-operator

---
# Harbor Container Registry Credentials
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: harbor-registry-credentials
  namespace: default
  labels:
    app.kubernetes.io/name: harbor
    app.kubernetes.io/component: secret
    environment: dev
spec:
  itemPath: "vaults/cicd/items/dev-harbor-registry"
  secretKey: ".dockerconfigjson"
  secretName: "harbor-registry-secret"
  secretType: "kubernetes.io/dockerconfigjson"
  secretLabels:
    app.kubernetes.io/name: harbor
    app.kubernetes.io/managed-by: onepassword-operator

---
# Grafana Admin Password
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: grafana-admin-password
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: secret
    environment: dev
spec:
  itemPath: "vaults/cicd/items/dev-grafana-admin"
  secretKey: "admin-password"
  secretName: "grafana-admin-credentials"
  secretType: "Opaque"
  secretLabels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/managed-by: onepassword-operator

---
# PostgreSQL Database Credentials
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: postgres-credentials
  namespace: database
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: secret
    environment: dev
spec:
  itemPath: "vaults/cicd/items/dev-postgresql-credentials"
  secretKey: "postgres-password"
  secretName: "postgres-credentials"
  secretType: "Opaque"
  secretLabels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/managed-by: onepassword-operator

---
# Redis Authentication
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: redis-auth
  namespace: database
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: secret
    environment: dev
spec:
  itemPath: "vaults/cicd/items/dev-redis-auth"
  secretKey: "redis-password"
  secretName: "redis-auth"
  secretType: "Opaque"
  secretLabels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/managed-by: onepassword-operator

---
# Slack Webhook for Monitoring Alerts
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: slack-webhook
  namespace: monitoring
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/component: secret
    environment: dev
spec:
  itemPath: "vaults/cicd/items/slack-monitoring-webhook"
  secretKey: "webhook-url"
  secretName: "slack-webhook"
  secretType: "Opaque"
  secretLabels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/managed-by: onepassword-operator

---
# Cloudflare Tunnel Token for External Access
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: cloudflare-tunnel-token
  namespace: cloudflare-tunnel
  labels:
    app.kubernetes.io/name: cloudflare-tunnel
    app.kubernetes.io/component: secret
    environment: dev
spec:
  itemPath: "vaults/cicd/items/dev-${CLUSTER_NAME}-tunnel-token"
  secretKey: "token"
  secretName: "cloudflare-tunnel-token"
  secretType: "Opaque"
  secretLabels:
    app.kubernetes.io/name: cloudflare-tunnel
    app.kubernetes.io/managed-by: onepassword-operator