# Homarr Helm Chart Values for Dev Environment
# Dashboard application - configured for root path operation

# Environment variables for proper root path operation
env:
  BASE_URL: "https://lab.techdufus.com"

# Resources for homelab environment
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 1Gi

# Enable persistence for configuration and SQLite database
homarrDatabase:
  enabled: true
  size: 1Gi

homarrImages:
  enabled: true
  size: 512Mi