# Homarr Helm Chart Values for Dev Environment
# Dashboard application - minimal overrides

# Resources for homelab environment
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

# Enable persistence for configuration and SQLite database
persistence:
  enabled: true
  size: 1Gi