# Homarr Helm Chart Values for Dev Environment
# Dashboard application - minimal overrides

# Service configuration (chart defaults to port 7575, ClusterIP)
service:
  type: ClusterIP
  port: 7575

# Resources for homelab environment
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

# Enable persistence for configuration and SQLite database
persistence:
  enabled: true
  size: 1Gi
  accessModes:
    - ReadWriteOnce

# Security context
securityContext:
  runAsNonRoot: true
  runAsUser: 65534
  runAsGroup: 65534
  fsGroup: 65534

# Container security context
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false  # Homarr needs write access for database
  runAsNonRoot: true
  runAsUser: 65534