# Metrics Server Helm Chart Values for Dev Environment
# Minimal overrides - only what differs from chart defaults

# Talos-specific configuration
args:
  - --kubelet-insecure-tls  # Required for Talos self-signed certificates

# Lower memory for homelab environment
resources:
  requests:
    memory: 128Mi  # Chart default is 200Mi
  limits:
    cpu: 500m
    memory: 512Mi