# Traefik Helm Chart Values for Dev Environment
# Minimal configuration with Gateway API support

# Deployment configuration
deployment:
  replicas: 1  # Single replica for dev

# Service configuration
service:
  type: LoadBalancer
  annotations:
    metallb.universe.tf/loadBalancerIPs: "10.0.20.200"  # Fixed IP from MetalLB pool

# Providers configuration - Gateway API and dashboard
providers:
  kubernetesGateway:
    enabled: true
    gateway:
      enabled: true
  kubernetesCRD:
    enabled: false  # Not using CRDs
  kubernetesIngress:
    enabled: false  # Not using Ingress

# Ports configuration
ports:
  web:
    port: 8000
    exposedPort: 80
    expose:
      default: true
    protocol: TCP
  websecure:
    port: 8443
    exposedPort: 443
    expose:
      default: true
    protocol: TCP
    http3:
      enabled: false
  traefik:
    port: 9000
    expose:
      default: false  # Dashboard disabled by default
    protocol: TCP

# Dashboard configuration
api:
  dashboard: true
  insecure: true  # Safe behind Cloudflare Tunnel
  
ingressRoute:
  dashboard:
    enabled: false  # We'll expose via Gateway API if needed

# Logs
logs:
  general:
    level: INFO
  access:
    enabled: true

# Resources for dev environment
resources:
  requests:
    cpu: 100m
    memory: 50Mi
  limits:
    cpu: 300m
    memory: 150Mi

# Pod disruption budget
podDisruptionBudget:
  enabled: false  # Not needed for single replica

# Autoscaling
autoscaling:
  enabled: false

# Security context
securityContext:
  capabilities:
    drop: [ALL]
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532

# Additional arguments
additionalArguments:
  - "--global.checknewversion=false"
  - "--global.sendanonymoususage=false"
  - "--api.insecure=true"  # Enable insecure dashboard (safe behind Cloudflare Tunnel)

# Create default GatewayClass for Traefik
gatewayClass:
  enabled: true
  name: traefik