---

- name: Check if user exists in docker group
  shell: |
    /usr/bin/getent group | awk -F":" '{print $1}' | grep -c "docker"
  register: docker_group
  failed_when: "docker_group.rc == 2"
  check_mode: no
  changed_when: false
  
- name: Install Flux Docker
  shell: |
    export usernew="{{ ansible_user }}"
    echo "1" | bash -i <(curl -s https://raw.githubusercontent.com/matthewjdegarmo/fluxnode-multitool/master/multitoolbox.sh)
  become: yes
  become_user: root
  args:
    executable: /bin/bash
  when: docker_group.stdout == "0"

- name: Deploy Install configuration file to flux node
  copy:
    src: "{{ ansible_hostname }}/install_conf.json"
    dest: "/home/{{ ansible_user }}/install_conf.json"

- name: Deploy flux update aliases to flux node
  template:
    src: "update_flux.j2"
    dest: /etc/profile.d/update_flux.sh
  become: yes

# - name: Ensure zelflux directory exists
#   file:
#     path: "/home/{{ ansible_user }}/zelflux"
#     state: directory

# - name: Ensure zelflux config directory exists
#   file:
#     path: "/home/{{ ansible_user }}/zelflux/config"
#     state: directory

# - name: Deploy uPnP configuration file to flux node
#   copy:
#     src: "{{ ansible_hostname }}/upnp.js"
#     dest: "/home/{{ ansible_user }}/zelflux/config/userconfig.js"

# - name: "Installing FluxNode - Go get some coffee. :)"
#   shell: |
#     echo "2" | bash -il <(curl -s https://raw.githubusercontent.com/RunOnFlux/fluxnode-multitool/master/multitoolbox.sh)
#   args:
#     executable: /bin/bash
#   # async: 28800 # 8 hours
#   become: yes
#   become_user: "{{ ansible_user }}"

- name: Ensure .fluxbenchmark directory exists
  file:
    path: "/home/{{ ansible_user }}/.fluxbenchmark"
    state: directory

- name: Deploy fluxbench.conf file
  copy:
    src: "{{ ansible_hostname }}/fluxbench.conf"
    dest: "/home/{{ ansible_user }}/.fluxbenchmark/fluxbench.conf"

- name: Deploy upnp_conf.json file
  copy:
    src: "{{ ansible_hostname }}/upnp_conf.json"
    dest: "/home/{{ ansible_user }}/upnp_conf.json"
    force: yes
# - name: Run multitoolbox to configure uPnP
#   shell: |
#     echo "14" | bash -ilc <(curl -s https://raw.githubusercontent.com/RunOnFlux/fluxnode-multitool/master/multitoolbox.sh)

- name: Ensure watchdog directory exists
  file:
    path: "/home/{{ ansible_user }}/watchdog"
    state: directory

- name: Deploy watchdog configuration file to flux node
  copy:
    src: "{{ ansible_hostname }}/watchdog.js"
    dest: "/home/{{ ansible_user }}/watchdog/config.js"

- name: Reload Watchdog
  shell: bash -ilc 'pm2 reload watchdog --watch'
  become: yes
  become_user: "{{ ansible_user }}"
  register: watchdog_reload
  failed_when: watchdog_reload.rc != 127

# PR uPnP auto-import / auto-install feature
# deploy uPnP config file
# run multitoolbox option 14

- name: Test for zelflux directory
  shell: |
    if [ -d "/home/{{ ansible_user }}/zelflux" ]; then
      echo "true"
    fi
  register: zelflux_dir
  changed_when: false

- name: Run update-flux command
  shell: bash -ilc 'update-flux'
  become: yes
  become_user: "{{ ansible_user }}"
  when: zelflux_dir.stdout == "true"
