apiVersion: v1
kind: Namespace
metadata:
  name: homarr
  labels:
    name: homarr
    app.kubernetes.io/name: homarr
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-traefik-routes
  namespace: homarr
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: traefik
  to:
    - group: ""
      kind: Service